spring.application.name=tictactoeapi

game.init.message=Game initialized with a %dx%d board. Player X to move first.
game.win.message=Player %s wins the game!
game.draw.message=The game is a Draw!
game.move.accepted.message=Move accepted.

game.error.validation.board.null=Invalid board state. Board cannot be null.
game.error.validation.board.size=Invalid board state. Array size must be a perfect square (e.g., 9, 16).

game.error.validation.position.taken=Position already taken! Choose an empty spot.
game.error.validation.position.out.of.bound=Out of bounds! Please choose a position between 0 and %d.

game.error.validation.invalid.player=Invalid player. Must be 'X' or 'O'.
